### PR TITLE
I'd actually be really surprised if this got accepted

### PR DESCRIPTION
**Pull request by DavidNyan10**
Its pretty shit, you can tweak and change it to make it much better.

### CODE REVIEW

**Comment by x6r** [comment]
i havent used animations anywhere else *because animations suck* so i think it will be inconsistent

also why `#6272a4` lol

**Comment by DavidNyan10** [comment]
I actually wanted something like [this](https://codepen.io/Smashbox/pen/VwMNYJo) without any animations but my brain cant get it to work. 

idk I found that in the dracula color palette lmao. it wasn't used and the other dracula-primary and dracula-secondary don't look good.

**Comment by x6r** [comment]
maybe you can post it as a css snippet but i think the current thingy suits the theme more

**Comment by DavidNyan10** [comment]
Ah ok.

**Pull request closed without merging**
